# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Creative Visualization-Opportunities Workshops
email: kerzner@sci.utah.edu

description: Supplemental Material
paper-title: A Framework for Creative Visualization-Opportunities Workshops
paper-authors: E. Kerzner, S. Goodwin, J. Dykes, S. Jones, and M. Meyer
paper-submission: Submitted to IEEE InfoVis 2018

baseurl: "CVOWorkshops" # the subpath of your site, e.g. /blog
url: "http://vdl.sci.utah.edu/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
github: [metadata]

# Build settings
markdown: kramdown
theme: minima

collections:
  methods:
    output: false
    attributes:
      output: false
  audits:
    output: false

repository: visdesignlab/CVOWorkshops.git
header_pages:
  - audit.md
  - methods.md
  - example.md
  - pitfalls.md
